GET {{URL}}/banks
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{URL}}/banks/1

###
POST {{URL}}/banks/create
Content-Type: application/json

{
  "name": "Lunar"
}

###
PUT {{URL}}/banks/update/1
Content-Type: application/json

{
  "name": "SpareBank"
}

###
DELETE {{URL}}/banks/delete/4

###
POST {{URL}}/auth/login/

{
    "username": "admin",
    "password": "1"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}